Repository nitroverso/mercapp-ui, pull requests merged in 2025-02, with the labels that each got.

#3 feat: Create product details route
  app/(dashboard)/cupboard/details/page.tsx
Labels: enhancement, bump-patch

#4 chore: Update versioning workflow
  .github/workflows/versioning.yml
Labels: enhancement, bump-minor

#5 chore: Update versioning workflow
  .github/workflows/versioning.yml
Labels: enhancement, bump-minor

#7 feat: Add create product feature
  app/(dashboard)/cupboard/add/page.tsx
  app/(dashboard)/cupboard/details/page.tsx
  app/(dashboard)/cupboard/modules/ProductDetails.tsx
  app/(dashboard)/layout.tsx
  app/AppInitializer.tsx
  app/lib/definitions/routes.ts
  app/lib/hooks/useProducts.ts
  app/lib/i18n/messages/en.json
  app/lib/i18n/messages/es.json
  app/ui/components/Card.tsx
  app/ui/components/ControlBox.tsx
  app/ui/components/form/Form.tsx
  app/ui/components/form/inputs/BaseInput.tsx
  app/ui/components/form/inputs/SelectInput.tsx
  app/ui/components/navigation/TopBar.tsx
Labels: enhancement, bump-minor

#8 feat: Add features update and delete products
  app/(dashboard)/cupboard/edit/page.tsx
  app/(dashboard)/cupboard/modules/ProductDetails.tsx
  app/(dashboard)/cupboard/modules/ProductsGroup.tsx
  app/AppInitializer.tsx
  app/lib/definitions/products.ts
  app/lib/definitions/routes.ts
  app/lib/definitions/ui.ts
  app/lib/hooks/useProducts.ts
  app/lib/i18n/messages/en.json
  app/lib/i18n/messages/es.json
  app/lib/services/serviceProducts.ts
  app/lib/store/UISlice.ts
  app/ui/components/Alert.tsx
  app/ui/components/AlertDialog.tsx
  app/ui/components/Card.tsx
  app/ui/components/form/Form.tsx
  app/ui/components/navigation/TopBar.tsx
Labels: enhancement, bump-minor

#9 feat: Add search products feature and UI enhacements
  app/(dashboard)/cupboard/modules/ProductsGroup.tsx
  app/(dashboard)/cupboard/modules/ProductsList.tsx
  app/(dashboard)/cupboard/page.tsx
  app/lib/definitions/ui.ts
  app/lib/hooks/useError.ts
  app/lib/hooks/useProducts.ts
  app/lib/i18n/messages/en.json
  app/lib/i18n/messages/es.json
  app/ui/components/ControlBox.tsx
  app/ui/components/form/Form.tsx
  app/ui/components/form/inputs/SearchInput.tsx
  app/ui/components/navigation/TopBar.tsx
  package-lock.json
  package.json
Labels: enhancement, bump-minor

#10 Promote dev v0.5.0 to main
  app/(dashboard)/cupboard/add/page.tsx
  app/(dashboard)/cupboard/details/page.tsx
  app/(dashboard)/cupboard/edit/page.tsx
  app/(dashboard)/cupboard/modules/ProductDetails.tsx
  app/(dashboard)/cupboard/modules/ProductsGroup.tsx
  app/(dashboard)/cupboard/modules/ProductsList.tsx
  app/(dashboard)/cupboard/page.tsx
  app/(dashboard)/layout.tsx
  app/AppInitializer.tsx
  app/lib/definitions/products.ts
  app/lib/definitions/routes.ts
  app/lib/definitions/ui.ts
  app/lib/hooks/useError.ts
  app/lib/hooks/useProducts.ts
  app/lib/i18n/messages/en.json
  app/lib/i18n/messages/es.json
  app/lib/services/serviceProducts.ts
  app/lib/store/UISlice.ts
  app/ui/components/Alert.tsx
  app/ui/components/AlertDialog.tsx
  app/ui/components/Card.tsx
  app/ui/components/ControlBox.tsx
  app/ui/components/form/Form.tsx
  app/ui/components/form/inputs/BaseInput.tsx
  app/ui/components/form/inputs/SearchInput.tsx
  app/ui/components/form/inputs/SelectInput.tsx
  app/ui/components/navigation/TopBar.tsx
  package-lock.json
  package.json
Labels: enhancement

#11 feat: Update middleware to include logo.png
  middleware.ts
Labels: enhancement, bump-patch

#12 Promote Dev v0.5.1 to Main
  middleware.ts
  package-lock.json
  package.json
Labels: enhancement
